### PR TITLE
Adds link shortener for skbio alpha div metrics

### PR DESCRIPTION
**Pull request by ChrisKeefe**
supports https://github.com/qiime2/q2-diversity/issues/167
Please let me know if I'm overlooking something, or you want this placed somewhere different in the `MAP`. 
I decided not to version this URL, to reduce upkeep and make the link shorter for cli viewing:

image

If a version number is preferred, though, we have enough room to make that happen:

image

### CODE REVIEW

**Review by thermokarst — COMMENTED** [review]
This is perfect, but I think maybe the current structure of this repo doesn't lend itself well to this kind of "permanent" link shortening. Maybe a new `_permanent.py` module would make sense here?

**Comment by ChrisKeefe** [comment]
I think we're good to go here. :)

**Review by thermokarst — CHANGES_REQUESTED** [review]
Great! Can you move `distro/core/aws-amis.txt` and `distro/core/virtualbox-images.txt` into the new module, too?

**Review by thermokarst — APPROVED** [review]

**Comment by thermokarst** [comment]
I'll deploy these changes in a bit, once I square away the new VM urls.

**Pull request merged**
